import type {
  AgentProvider,
  AgentStreamEvent,
} from "@harness/core";
import { AgentCliError } from "./model-cli-errors.ts";
import type {
  ModelCliAdapter,
  ModelCliRequest,
  ModelCliResult,
} from "./model-cli-types.ts";

/**
 * Phase 8 — deterministic adapter for smoke tests, CI, and developer
 * loops without a real CLI. Each scripted scenario emits one or more
 * `raw` chunks followed by an intermediate `assistant_text` event containing
 * the harness_agent_plan fenced JSON, then a `result` event that commits it.
 *
 * Scenarios:
 * - `ok-file-write` — one file_write action, accepted.
 * - `ok-shell` — one shell action, accepted.
 * - `ok-answer-only` — no proposed actions (information-only response).
 * - `bad-traversal` — file_write whose path traversal will be rejected
 *   by validateProposedActionDetails (filter, not all-or-nothing).
 * - `parse-error` — emits a fenced block with malformed JSON to test
 *   the AGENT_INVALID_OUTPUT path.
 * - `aborted` — never resolves on its own; only honors AbortSignal so
 *   smoke tests can exercise cancelInvocation.
 * - `spawn-failed` — rejects synchronously like a missing binary.
 */
export type FakeScenario =
  | "ok-file-write"
  | "ok-shell"
  | "ok-answer-only"
  | "bad-traversal"
  | "parse-error"
  | "aborted"
  | "spawn-failed";

export interface FakeModelCliAdapterOptions {
  scenario: FakeScenario;
  /**
   * Override per-chunk delay (default 10ms). Tests can drop to 0 to
   * resolve in a single tick; live demo runs use a small delay so the
   * UI actually shows a stream.
   */
  chunkDelayMs?: number;
  /**
   * Final latency reported back in the result. Defaults to ~50ms.
   */
  finalLatencyMs?: number;
}

const sleep = (ms: number, signal?: AbortSignal): Promise<void> =>
  new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(new AgentCliError("AGENT_CANCELLED", "aborted", "aborted"));
      return;
    }
    const timer = setTimeout(() => {
      signal?.removeEventListener("abort", onAbort);
      resolve();
    }, ms);
    const onAbort = (): void => {
      clearTimeout(timer);
      reject(new AgentCliError("AGENT_CANCELLED", "aborted", "aborted"));
    };
    signal?.addEventListener("abort", onAbort, { once: true });
  });

const fence = (tag: string, body: string): string =>
  ["```" + tag, body, "```"].join("\n");

const samplePlan = (
  scenario: Exclude<FakeScenario, "aborted" | "spawn-failed" | "parse-error">,
  request: ModelCliRequest,
): string => {
  if (scenario === "ok-file-write") {
    return JSON.stringify(
      {
        summary: "Add a fake README file.",
        assumptions: ["target directory is writable"],
        steps: [
          {
            title: "Create README.md",
            rationale: "Documents the fake run",
            risk: "low",
          },
        ],
        proposedActions: [
          {
            type: "file_write",
            path: "README.smoke.md",
            after: "# Smoke run\n\nGenerated by FakeModelCliAdapter.\n",
            rationale: "Smoke test artifact",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "ok-shell") {
    return JSON.stringify(
      {
        summary: "Print working dir.",
        assumptions: [],
        steps: [
          { title: "pwd", rationale: "Verify cwd", risk: "low" },
        ],
        proposedActions: [
          {
            type: "shell",
            command: "node",
            args: ["-e", "console.log(process.cwd())"],
            rationale: "Echo cwd inside sandbox",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "ok-answer-only") {
    return JSON.stringify(
      {
        summary: "Already configured; no action needed.",
        assumptions: [],
        steps: [],
        proposedActions: [],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  // bad-traversal
  return JSON.stringify(
    {
      summary: "Attempt path traversal.",
      assumptions: [],
      steps: [],
      proposedActions: [
        {
          type: "file_write",
          path: "../../../etc/passwd",
          after: "should be rejected",
          rationale: "Adversarial input",
        },
      ],
      suggestedQualityChecks: [],
      questions: [],
    },
    null,
    2,
  );
};

const sampleOutput = (scenario: FakeScenario, request: ModelCliRequest): string => {
  if (scenario === "parse-error") {
    return [
      "I will emit invalid JSON to exercise the parser.",
      fence("harness_agent_plan", "{ this is : not json"),
    ].join("\n\n");
  }
  if (scenario === "aborted" || scenario === "spawn-failed") {
    return "";
  }
  const planJson = samplePlan(scenario, request);
  return [
    `Thinking through ${scenario}…`,
    "",
    "Here is the plan:",
    "",
    fence("harness_agent_plan", planJson),
  ].join("\n");
};

export class FakeModelCliAdapter implements ModelCliAdapter {
  private readonly options: FakeModelCliAdapterOptions;
  constructor(options: FakeModelCliAdapterOptions) {
    this.options = options;
  }

  async invoke(
    request: ModelCliRequest,
    onEvent: (e: AgentStreamEvent) => void,
    signal?: AbortSignal,
  ): Promise<ModelCliResult> {
    const start = Date.now();
    const { scenario } = this.options;
    const chunkDelay = this.options.chunkDelayMs ?? 10;
    const finalLatency = this.options.finalLatencyMs ?? 50;

    onEvent({
      type: "started",
      invocationId: request.invocationId,
      provider: request.modelConfig.provider,
      model: request.modelConfig.model,
    });

    if (scenario === "spawn-failed") {
      throw new AgentCliError(
        "AGENT_SPAWN_FAILED",
        "spawn_failed",
        "fake adapter scenario=spawn-failed",
      );
    }

    if (scenario === "aborted") {
      // Wait forever on the signal so callers can verify the cancel path.
      await new Promise<void>((_resolve, reject) => {
        const onAbort = (): void => {
          reject(new AgentCliError("AGENT_CANCELLED", "aborted", "aborted"));
        };
        if (signal?.aborted) onAbort();
        else signal?.addEventListener("abort", onAbort, { once: true });
      });
      // Unreachable — the abort listener always rejects.
      throw new AgentCliError("AGENT_CANCELLED", "aborted", "aborted");
    }

    const stdout = sampleOutput(scenario, request);
    const chunks = chunkString(stdout, 64);
    for (const chunk of chunks) {
      await sleep(chunkDelay, signal);
      onEvent({
        type: "raw",
        invocationId: request.invocationId,
        source: "stdout",
        text: chunk,
      });
    }
    await sleep(chunkDelay, signal);
    onEvent({
      type: "assistant_text",
      invocationId: request.invocationId,
      text: stdout,
    });
    onEvent({
      type: "result",
      invocationId: request.invocationId,
      latencyMs: Date.now() - start,
      costEstimate: 0,
    });

    const provider: AgentProvider = request.modelConfig.provider;
    return {
      provider,
      model: request.modelConfig.model,
      exitCode: 0,
      stdout,
      stderr: "",
      normalizedEvents: [],
      latencyMs: finalLatency,
      costEstimate: 0,
    };
  }
}

const chunkString = (s: string, n: number): string[] => {
  if (s.length === 0) return [];
  const out: string[] = [];
  for (let i = 0; i < s.length; i += n) {
    out.push(s.slice(i, i + n));
  }
  return out;
};
