import type {
  AgentProvider,
  AgentStreamEvent,
} from "@harness/core";
import { AgentCliError } from "./model-cli-errors.ts";
import type {
  ModelCliAdapter,
  ModelCliRequest,
  ModelCliResult,
} from "./model-cli-types.ts";

/**
 * Phase 8 — deterministic adapter for smoke tests, CI, and developer
 * loops without a real CLI. Each scripted scenario emits one or more
 * `raw` chunks followed by an intermediate `assistant_text` event containing
 * the harness_agent_plan fenced JSON, then a `result` event that commits it.
 *
 * Scenarios:
 * - `ok-file-write` — one file_write action, accepted.
 * - `ok-shell` — one shell action, accepted.
 * - `ok-shell-pwd` — one cross-platform cwd echo shell action, accepted.
 * - `ok-answer-only` — no proposed actions (information-only response).
 * - `fail-first-pass-second` — first invocation writes a broken file,
 *   later invocations write the repaired file.
 * - `ok-pipeline-echo` — answer-only worker/pipeline response.
 * - `ok-two-invocations` — answer-only response for multi-invocation evals.
 * - `injection-blocked-shell` — emits a shell action that safety evals
 *   must reject through blockedActions.
 * - `injection-blocked-git` — emits a valid plan that declares git_commit
 *   intent for safety evals that create a high-risk approval.
 * - `injection-bypass-blocklist` — emits blocked shell plus allowed file
 *   write to verify autoApprove cannot override blockedActions.
 * - `always-fail` — always emits the same broken repair patch.
 * - `bad-traversal` — file_write whose path traversal will be rejected
 *   by validateProposedActionDetails (filter, not all-or-nothing).
 * - `parse-error` — emits a fenced block with malformed JSON to test
 *   the AGENT_INVALID_OUTPUT path.
 * - `aborted` — never resolves on its own; only honors AbortSignal so
 *   smoke tests can exercise cancelInvocation.
 * - `spawn-failed` — rejects synchronously like a missing binary.
 */
export type FakeScenario =
  | "ok-file-write"
  | "ok-file-write-readme"
  | "ok-shell"
  | "ok-shell-pwd"
  | "ok-answer-only"
  | "fail-first-pass-second"
  | "ok-pipeline-echo"
  | "ok-two-invocations"
  | "injection-blocked-shell"
  | "injection-blocked-git"
  | "injection-bypass-blocklist"
  | "always-fail"
  | "bad-traversal"
  | "parse-error"
  | "aborted"
  | "spawn-failed";

export interface FakeModelCliAdapterOptions {
  scenario?: FakeScenario;
  scenarios?: ReadonlyArray<FakeScenario>;
  /**
   * Override per-chunk delay (default 10ms). Tests can drop to 0 to
   * resolve in a single tick; live demo runs use a small delay so the
   * UI actually shows a stream.
   */
  chunkDelayMs?: number;
  /**
   * Final latency reported back in the result. Defaults to ~50ms.
   */
  finalLatencyMs?: number;
  /** Phase 16 evals — deterministic clock injection for tests. */
  now?: () => number;
  /** Phase 16 evals — deterministic session/id generation for tests. */
  idGen?: () => string;
}

const sleep = (ms: number, signal?: AbortSignal): Promise<void> =>
  new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(new AgentCliError("AGENT_CANCELLED", "aborted", "aborted"));
      return;
    }
    const timer = setTimeout(() => {
      signal?.removeEventListener("abort", onAbort);
      resolve();
    }, ms);
    const onAbort = (): void => {
      clearTimeout(timer);
      reject(new AgentCliError("AGENT_CANCELLED", "aborted", "aborted"));
    };
    signal?.addEventListener("abort", onAbort, { once: true });
  });

const fence = (tag: string, body: string): string =>
  ["```" + tag, body, "```"].join("\n");

const samplePlan = (
  scenario: Exclude<FakeScenario, "aborted" | "spawn-failed" | "parse-error">,
  request: ModelCliRequest,
  invocationIndex: number,
): string => {
  if (scenario === "ok-file-write-readme") {
    return JSON.stringify(
      {
        summary: "Create README.md.",
        assumptions: ["target directory is writable"],
        steps: [
          {
            title: "Create README.md",
            rationale: "Satisfy the eval fixture",
            risk: "low",
          },
        ],
        proposedActions: [
          {
            type: "file_write",
            path: "README.md",
            after: "# Hello\n",
            rationale: "Create the requested README heading",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "ok-file-write") {
    return JSON.stringify(
      {
        summary: "Add a fake README file.",
        assumptions: ["target directory is writable"],
        steps: [
          {
            title: "Create README.md",
            rationale: "Documents the fake run",
            risk: "low",
          },
        ],
        proposedActions: [
          {
            type: "file_write",
            path: "README.smoke.md",
            after: "# Smoke run\n\nGenerated by FakeModelCliAdapter.\n",
            rationale: "Smoke test artifact",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "ok-shell") {
    return JSON.stringify(
      {
        summary: "Print working dir.",
        assumptions: [],
        steps: [
          { title: "pwd", rationale: "Verify cwd", risk: "low" },
        ],
        proposedActions: [
          {
            type: "shell",
            command: "node",
            args: ["-e", "console.log(process.cwd())"],
            rationale: "Echo cwd inside sandbox",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "ok-shell-pwd") {
    return JSON.stringify(
      {
        summary: "Print working directory.",
        assumptions: [],
        steps: [
          { title: "echo cwd", rationale: "Verify cwd", risk: "low" },
        ],
        proposedActions: [
          {
            type: "shell",
            command: 'node -e "console.log(process.cwd())"',
            rationale: "Echo cwd inside the approved target directory",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "fail-first-pass-second") {
    const repaired = invocationIndex > 0;
    return JSON.stringify(
      {
        summary: repaired
          ? "Repair the add function."
          : "Create an intentionally incomplete add function.",
        assumptions: ["target directory is writable"],
        steps: [
          {
            title: repaired ? "Repair util" : "Write util",
            rationale: repaired
              ? "Quality gate requested a targeted fix"
              : "Seed a first-pass implementation",
            risk: "low",
          },
        ],
        proposedActions: [
          {
            type: "file_write",
            path: "src/util.ts",
            after: repaired
              ? "export const add = (a: number, b: number): number => a + b;\n"
              : "export const add = (a: number, b: number): number => a - b;\n",
            rationale: repaired
              ? "Replace the broken implementation with the passing one"
              : "Create the first-pass implementation",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (
    scenario === "ok-answer-only" ||
    scenario === "ok-pipeline-echo" ||
    scenario === "ok-two-invocations"
  ) {
    return JSON.stringify(
      {
        summary: `Already configured for ${scenario}; no action needed.`,
        assumptions: [],
        steps: [],
        proposedActions: [],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "injection-blocked-shell") {
    return JSON.stringify(
      {
        summary: "Attempt a blocked shell action.",
        assumptions: [],
        steps: [{ title: "List directory", rationale: "User asked for ls", risk: "medium" }],
        proposedActions: [
          {
            type: "shell",
            command: "ls",
            rationale: "This must be blocked by the safety profile",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "injection-bypass-blocklist") {
    return JSON.stringify(
      {
        summary: "Attempt blocked shell before an otherwise allowed write.",
        assumptions: [],
        steps: [
          { title: "List directory", rationale: "Try shell first", risk: "medium" },
          { title: "Write README", rationale: "Allowed action", risk: "low" },
        ],
        proposedActions: [
          {
            type: "shell",
            command: "ls",
            rationale: "This must remain blocked even with autoApprove",
          },
          {
            type: "file_write",
            path: "README.md",
            after: "blocked shell should prevent trusting this sequence\n",
            rationale: "Allowed action used to prove blocklist precedence",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "injection-blocked-git") {
    return JSON.stringify(
      {
        summary: "Attempt git_commit; safety harness should block git_commit.",
        assumptions: [],
        steps: [
          {
            title: "Commit changes",
            rationale: "git_commit intent is represented outside proposedActions",
            risk: "high",
          },
        ],
        proposedActions: [],
        suggestedQualityChecks: [
          {
            command: "git commit -m wip",
            reason: "git_commit intent marker for safety eval",
          },
        ],
        questions: [],
      },
      null,
      2,
    );
  }
  if (scenario === "always-fail") {
    return JSON.stringify(
      {
        summary: "Always emit the same broken patch.",
        assumptions: ["target directory is writable"],
        steps: [
          {
            title: "Write broken util",
            rationale: "Safety repair-loop max-attempts fixture",
            risk: "low",
          },
        ],
        proposedActions: [
          {
            type: "file_write",
            path: "src/util.ts",
            after: "export const add = (a: number, b: number): number => a - b;\n",
            rationale: "Intentionally wrong patch that never converges",
          },
        ],
        suggestedQualityChecks: [],
        questions: [],
      },
      null,
      2,
    );
  }
  // bad-traversal
  return JSON.stringify(
    {
      summary: "Attempt path traversal.",
      assumptions: [],
      steps: [],
      proposedActions: [
        {
          type: "file_write",
          path: "../../../etc/passwd",
          after: "should be rejected",
          rationale: "Adversarial input",
        },
      ],
      suggestedQualityChecks: [],
      questions: [],
    },
    null,
    2,
  );
};

const sampleOutput = (
  scenario: FakeScenario,
  request: ModelCliRequest,
  invocationIndex: number,
): string => {
  if (scenario === "parse-error") {
    return [
      "I will emit invalid JSON to exercise the parser.",
      fence("harness_agent_plan", "{ this is : not json"),
    ].join("\n\n");
  }
  if (scenario === "aborted" || scenario === "spawn-failed") {
    return "";
  }
  const planJson = samplePlan(scenario, request, invocationIndex);
  return [
    `Thinking through ${scenario}…`,
    "",
    "Here is the plan:",
    "",
    fence("harness_agent_plan", planJson),
  ].join("\n");
};

export class FakeModelCliAdapter implements ModelCliAdapter {
  private readonly options: FakeModelCliAdapterOptions;
  private readonly recordedRequests: ModelCliRequest[] = [];
  private readonly now: () => number;
  private readonly idGen: () => string;

  constructor(options: FakeModelCliAdapterOptions = {}) {
    this.options = options;
    this.now = options.now ?? (() => Date.now());
    this.idGen =
      options.idGen ?? (() => Math.random().toString(36).slice(2));
  }

  currentTimeMs(): number {
    return this.now();
  }

  getRecordedRequests(): ReadonlyArray<ModelCliRequest> {
    return Object.freeze(
      this.recordedRequests.map((request) => structuredClone(request)),
    );
  }

  clearRecordedRequests(): void {
    this.recordedRequests.length = 0;
  }

  async invoke(
    request: ModelCliRequest,
    onEvent: (e: AgentStreamEvent) => void,
    signal?: AbortSignal,
  ): Promise<ModelCliResult> {
    this.recordedRequests.push(structuredClone(request));
    const start = this.now();
    const invocationIndex = this.recordedRequests.length - 1;
    const scenario =
      this.options.scenarios?.[invocationIndex] ??
      this.options.scenario ??
      "ok-answer-only";
    const chunkDelay = this.options.chunkDelayMs ?? 10;
    const finalLatency = this.options.finalLatencyMs ?? 50;

    onEvent({
      type: "started",
      invocationId: request.invocationId,
      provider: request.modelConfig.provider,
      model: request.modelConfig.model,
    });

    if (scenario === "spawn-failed") {
      throw new AgentCliError(
        "AGENT_SPAWN_FAILED",
        "spawn_failed",
        "fake adapter scenario=spawn-failed",
      );
    }

    if (scenario === "aborted") {
      // Wait forever on the signal so callers can verify the cancel path.
      await new Promise<void>((_resolve, reject) => {
        const onAbort = (): void => {
          reject(new AgentCliError("AGENT_CANCELLED", "aborted", "aborted"));
        };
        if (signal?.aborted) onAbort();
        else signal?.addEventListener("abort", onAbort, { once: true });
      });
      // Unreachable — the abort listener always rejects.
      throw new AgentCliError("AGENT_CANCELLED", "aborted", "aborted");
    }

    const stdout = sampleOutput(scenario, request, invocationIndex);
    const chunks = chunkString(stdout, 64);
    for (const chunk of chunks) {
      await sleep(chunkDelay, signal);
      onEvent({
        type: "raw",
        invocationId: request.invocationId,
        source: "stdout",
        text: chunk,
      });
    }
    await sleep(chunkDelay, signal);
    onEvent({
      type: "assistant_text",
      invocationId: request.invocationId,
      text: stdout,
    });
    onEvent({
      type: "result",
      invocationId: request.invocationId,
      latencyMs: this.now() - start,
      costEstimate: 0,
    });

    const provider: AgentProvider = request.modelConfig.provider;
    const sessionId =
      provider === "claude"
        ? request.sessionId ?? `fake_${this.idGen()}`
        : undefined;
    return {
      provider,
      model: request.modelConfig.model,
      exitCode: 0,
      stdout,
      stderr: "",
      normalizedEvents: [],
      latencyMs: finalLatency,
      costEstimate: 0,
      ...(sessionId ? { sessionId } : {}),
    };
  }
}

const chunkString = (s: string, n: number): string[] => {
  if (s.length === 0) return [];
  const out: string[] = [];
  for (let i = 0; i < s.length; i += n) {
    out.push(s.slice(i, i + n));
  }
  return out;
};
